In [3]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "exams.csv"

# Load the latest version
df = kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "rkiattisak/student-performance-in-mathematics",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

Using Colab cache for faster access to the 'student-performance-in-mathematics' dataset.

In [20]:
import pandas as pd

In [4]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group D,some college,standard,completed,59,70,78
1,male,group D,associate's degree,standard,none,96,93,87
2,female,group D,some college,free/reduced,none,57,76,77
3,male,group B,some college,free/reduced,none,70,70,63
4,female,group D,associate's degree,standard,none,83,85,86

In [7]:
# Tabla para la variable genero
# Esta es una tabla de frecuencia simple
tabla_gender = df['gender'].value_counts()
print(tabla_gender)

gender
male      508
female    492
Name: count, dtype: int64

In [8]:
# esta opción nos permite determinar los diferentes valores que asume una determinada variable.
df['race/ethnicity'].unique()

array(['group D', 'group B', 'group C', 'group E', 'group A'],
      dtype=object)

In [9]:
# Tabla de frecuencia para la variable Raza ('race/ethnicity)
tabla_raza = df['race/ethnicity'].value_counts()
print(tabla_raza)

race/ethnicity
group C    323
group D    257
group B    198
group E    143
group A     79
Name: count, dtype: int64

In [10]:
# Notemos si queremos realizar una tabla de frecuencia simple para la variable math score

Tabla_math_score = df['math score'].value_counts()
print(Tabla_math_score)

math score
62    32
74    30
59    29
67    29
68    28
      ..
27     1
25     1
21     1
24     1
15     1
Name: count, Length: 79, dtype: int64

In [ ]:
# Cuando tenemos una variable cuantitativa con muchos valores diferentes
# se hace necesario realizar tablas de frecuencias de datos agrupados.

# Tablas de frecuencias para datos agrupados

In [11]:
x = [77, 18, 63, 84, 34, 59, 59, 54, 56, 36, 26, 34, 44,
        41, 58, 58, 53, 51, 62, 43, 52, 53, 63, 62, 65, 51, 62, 60, 68, 45, 65, 83, 71, 63, 58, 61]

In [12]:
len(x)

36

In [16]:
max_value = max(x)
min_value = min(x)
print(max_value)
print(min_value)

# definimos el número de clases:
num_clases = 7

# hallamos el ancho (amplitud) de la clase
A = (max_value - min_value) / num_clases
print(A)

84
18
9.428571428571429

In [17]:
A = 9.43
# Definir los límites de clase
limites = [18 + A * i for i in range(num_clases+1)]

In [18]:
limites

[18.0, 27.43, 36.86, 46.29, 55.72, 65.15, 74.58, 84.00999999999999]

In [21]:
# Crear el DataFrame con las frecuencias
tabla = pd.cut(x, bins=limites, include_lowest = True, right=False) # pd.cut() es una función que permite dividir los datos
                                                                    # en los diferentes límites

tabla = pd.value_counts(tabla, sort=False).reset_index()  #El parámetro sort se debe seleccionar como falso para que no ordene
                                                   # los intervalos en orden descendente según las frecuencias, sino que
                                                    # conserve el orden en que fueron definidos

'''Después de usar value_counts, el resultado puede tener un índice que consiste en valores distintos
del índice entero estándar o puede estar basado en una de las columnas del DataFrame.
Usar .reset_index() devuelve el índice a la forma estándar, y permite realizar operaciones sin
ningún inconveniente'''

tabla

/tmp/ipykernel_4580/902524117.py:5: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  tabla = pd.value_counts(tabla, sort=False).reset_index()  #El parámetro sort se debe seleccionar como falso para que no ordene

            index  count
0   [18.0, 27.43)      2
1  [27.43, 36.86)      3
2  [36.86, 46.29)      4
3  [46.29, 55.72)      6
4  [55.72, 65.15)     16
5  [65.15, 74.58)      2
6  [74.58, 84.01)      3

In [22]:
tabla.columns = ['Clases', 'Frec Abs']

In [23]:
tabla

           Clases  Frec Abs
0   [18.0, 27.43)         2
1  [27.43, 36.86)         3
2  [36.86, 46.29)         4
3  [46.29, 55.72)         6
4  [55.72, 65.15)        16
5  [65.15, 74.58)         2
6  [74.58, 84.01)         3

In [24]:
tabla['Frec Abs Acum'] = tabla['Frec Abs'].cumsum()

In [25]:
tabla

           Clases  Frec Abs  Frec Abs Acum
0   [18.0, 27.43)         2              2
1  [27.43, 36.86)         3              5
2  [36.86, 46.29)         4              9
3  [46.29, 55.72)         6             15
4  [55.72, 65.15)        16             31
5  [65.15, 74.58)         2             33
6  [74.58, 84.01)         3             36

In [26]:
tabla['Frec Rel'] = tabla['Frec Abs'] / len(x)

In [27]:
tabla

           Clases  Frec Abs  Frec Abs Acum  Frec Rel
0   [18.0, 27.43)         2              2  0.055556
1  [27.43, 36.86)         3              5  0.083333
2  [36.86, 46.29)         4              9  0.111111
3  [46.29, 55.72)         6             15  0.166667
4  [55.72, 65.15)        16             31  0.444444
5  [65.15, 74.58)         2             33  0.055556
6  [74.58, 84.01)         3             36  0.083333

In [28]:
pd.set_option('display.precision', 2) # Configuramos Pandas para mostrar solo dos decimales en los valores numéricos

In [29]:
tabla

           Clases  Frec Abs  Frec Abs Acum  Frec Rel
0   [18.0, 27.43)         2              2      0.06
1  [27.43, 36.86)         3              5      0.08
2  [36.86, 46.29)         4              9      0.11
3  [46.29, 55.72)         6             15      0.17
4  [55.72, 65.15)        16             31      0.44
5  [65.15, 74.58)         2             33      0.06
6  [74.58, 84.01)         3             36      0.08

In [31]:
# Frecuencia relativa acumulada

tabla['Frec Rel Acum'] = tabla['Frec Rel'].cumsum()
#

In [32]:
tabla

           Clases  Frec Abs  Frec Abs Acum  Frec Rel  Frec Rel Acum
0   [18.0, 27.43)         2              2      0.06           0.06
1  [27.43, 36.86)         3              5      0.08           0.14
2  [36.86, 46.29)         4              9      0.11           0.25
3  [46.29, 55.72)         6             15      0.17           0.42
4  [55.72, 65.15)        16             31      0.44           0.86
5  [65.15, 74.58)         2             33      0.06           0.92
6  [74.58, 84.01)         3             36      0.08           1.00

In [34]:
# Creemos la marca
tabla['Marca de Clase'] = tabla['Clases'].apply(lambda x: x.mid)
#

In [35]:
tabla

,Clases,Frec Abs,Frec Abs Acum,Frec Rel,Frec Rel Acum,Marca de Clase
0,"[18.0, 27.43)",2,2,0.06,0.06,22.71
1,"[27.43, 36.86)",3,5,0.08,0.14,32.14
2,"[36.86, 46.29)",4,9,0.11,0.25,41.58
3,"[46.29, 55.72)",6,15,0.17,0.42,51.00
4,"[55.72, 65.15)",16,31,0.44,0.86,60.44
5,"[65.15, 74.58)",2,33,0.06,0.92,69.87
6,"[74.58, 84.01)",3,36,0.08,1.00,79.30